<?php

namespace App\Command;

use App\Core\Config\Config;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class TemplateClearCache extends Command
{
    protected static $defaultName = 'template:clear-cache';

    protected function configure()
    {
        $this
            ->setDescription('Clear template\'s cache')
            ->setHelp('This command allows you to clear the cache generated by Twig')
        ;
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $cacheDirectory = realpath(Config::config('template_cache'));

        if (is_dir($cacheDirectory)) {
            $isWindows = strtoupper(substr(PHP_OS, 0, 3)) === 'WIN';
            if ($isWindows) {
                $cmd = sprintf('rd /s /q %s', $cacheDirectory);
            } else {
                $cmd = sprintf('rm -Rf %s', $cacheDirectory);
            }

            exec($cmd);
        }

        return 0;
    }
}
